### ISSUE TITLE
Will the VITON-HD dataset be public?

### ISSUE THREAD

**Issue by genghisun** [ChongjianGE/DCTON#1]
Hi, Thansk for your great work and great results! Just can't wait to try it!

Since you mentioned the VITON-HD dataset in the paper, I would like to ask how you obtained it? Was it by direct scaling 2x or some Super Resolution methods used? And will that dataset be public accessible?

**Comment by ChongjianGE** [comment]
Thanks for your interest in our work.

We have the dataset with 1024*512 resolution and downsample it by 2x to obtain the VITON-HD.  And we adopt the representative parsing model, and Densepose model to collect the other supplementary data (e.g., parsing labels, Densepose descriptors ). But we are sorry that we don't have the right to make the dataset publicly accessible since the author has restricted the data distribution.  

We recommend asking the author of [VITON](https://github.com/xthan/VITON#viton-an-image-based-virtual-try-on-network) for original VITON-HD resources.

**Comment by jokerlc** [comment]
@ChongjianGE Hi, can you provide the parsing model and densepose model that you have used ?

**Comment by wang674** [comment]
> @ChongjianGE Hi, can you provide the parsing model and densepose model that you have used ?

Hello, do you know which model densepose uses? @jokerlc @ChongjianGE
