### ISSUE TITLE
can I see your demo for training? 

### ISSUE THREAD

**Issue by CuiShaohua** [ChongjianGE/DCTON#10]

**Comment by CuiShaohua** [comment]
if you want to optimized the micro-part clearity, e.g. hands part, waht would you like to do?

**Comment by ChongjianGE** [comment]
currently, we don't have bandwith to work on the training code. Thanks for the understanding.

**Comment by ChongjianGE** [comment]
Hi Shaohua@CuiShaohua ,
BTW, I am writing to inquire if you still have the pretrained weights that we provided before.
 
The reason for my inquiry is that the original provided weights were kept in the university Google Drive, which has since been turned off. Our university has recently switched to the Onedrive service and as a result, the original link for the weights is no longer available, which means we have lost our files.
 
Given that you implemented this project before, I am hopeful that you may still have the weights that we provided. If that is the case, we would be incredibly grateful if you could share the files with us again.
